Bumped lib versions and corss compiled 2.12 2.13.
carpe/scalambda pull request #56
Opened 2022-08-12 11:02 UTC by IvoSaraiva

2022-08-12 16:18 UTC, rui-ribeiro requested changes
LGTM, did we test it on of our projects?

2022-08-12 16:18 UTC, rui-ribeiro commented on project/versions.scala
> +  lazy val circeVersion = "0.14.2"
Can we move this to build.sbt? It's more consistent regarding the others projects

2022-08-12 16:18 UTC, rui-ribeiro commented on plugin/src/main/scala/io/carpe/scalambda/assemble/ScalambdaAssemblyJVM.scala
> +      applyStrategies(mappings, ao.mergeStrategy, ao.assemblyDirectory.get, log)
Is this get safe?

2022-08-23 15:24 UTC, jguitana approved these changes

2022-08-24 08:33 UTC, cdheytornobre commented on plugin/src/main/scala/io/carpe/scalambda/assemble/AssemblySettings.scala
> +    (key / test).value
Is this line needed? Just trying to understand the code. lol

2025-07-29 17:49 UTC, closed without merging